server:
  port: ${PORT:8080}
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  redis:
    host: ${REDIS_HOST}
    database: 1
    password: ${REDIS_PASSWORD}
    port: 6379
    lettuce:
      pool:
        max-active: 5
        max-idle: 10
        min-idle: 5
        max-wait: 6000
    connect-timeout: 10000
# mybatis plus
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  typeEnumsPackage: com.baomidou.mybatisplus.core.enums
  global-config:
    db-config:
      id-type: ASSIGN_ID
#需要排除的路径
ignore:
  ignore-urls:
    - /actuator/**
logging:
  level:
    com:
      ewo:
        admin:
          auth: debug
    springfox:
      documentation:
        spring:
          web:
            readers:
              operation:
                CachingOperationNameGenerator: error
    org:
      springframework:
        security: debug